# Copyright (C) 2003 - 2021  Spurgeon Woods LLC
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

"""This module implements the Transcript Images class."""

__author__ = 'David Woods <dwoods@transana.com>'

#----------------------------------------------------------------------
# This file was generated by C:\Program Files (x86)\Python 26-32\Scripts\img2py
#

from wx.lib.embeddedimage import PyEmbeddedImage

ArtProv_ERROR = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAACW9J"
    "REFUWIXFl1lsHdUZx3/nzNx9sa/3+PrGcRZMnKQIJ7abEqiQgkSBLA8IlYgHBFnIA4gWEULT"
    "SJEoBSQUVCQCWfpSVVRFJWlTEaryAAUKiUNMQhInDnGcxLtjx/a9vsvcmTmnD/faclgKrVT1"
    "k45Go5k58zvf/P/fnE8IafB9YvOmjdoAtJQIpUBKlFIASClBqZlrLrBv/wHxfeYV3wWwedNG"
    "HYlEkFLS2NjI/PnzicfjVJSXE4lGAUglk4yOjdHf38+lS5fo6upCKUUqlfpOkG8FeGzLZh2L"
    "xSiJRmlpbWXpkiXo62NYff3kR8ewr1/HnUySz2QwS6L4qivx1iYIxOcgYzHOdHZyvL2dyWSS"
    "8fFx3ti77xtBvhFg68ZH9ZxEguXNzbS1tJA734UzOoJvfJLcqZOIsTFEJofWDkppHMAWEkuA"
    "FY0SuPNOIo034atLcOr0aU50dDDY28vrB377NYivAWzZvEnPq6/nJ/fcQ1xrUl0XiFg5sh9+"
    "iDE6WvjuChwUGnAB7WhcoVDaRSnISklOSiKrV1Nzx48Z9pi8e+QIl69cYe++/eJbAbZufFTP"
    "bWjgwQ0bEGfOICeTiJMn4UIXWimU1jcMrRTO9LlSKEAphas12nXJmiZT0uCmrY/hWbGCP7z5"
    "Jld7em7IxAzAY1s269raWtauXUusrw85PIz69CjmyCD5TI58Nov0+cDnQ7suSoOjFcpVKIoQ"
    "QmNnLdx0FuU1wefDFoKsNGh84nHSixZx+PBhBgYGZjQhp0lisRjLm5uJa4114QL62DEYGiQ9"
    "MUGgvp7Etm34GxrITFzHUQrbsXFcF0cr8q6L7bpkJ5IYFRUknnyC8E2NZK+PoSwLw7I4+5tX"
    "qcnnWd7cTCwWm8m6hILVSqJR2lpaGPnkE/zXruH29mOlUoTqG6h67jn8a9YQf/55gvUNpMbG"
    "sLUm77rkbRtXueQmJ/FUVlL21FM469cS2/Y0kaalZJNJnLwFmTQdL7xIW0sLJUX7zgBEIhFW"
    "tLRgXe7Bc7UX59Qp7MwUnqoq5rz8MtTUFO6uqmLB7leI3Hwz2aIgHdfFmhjHO6eWih07cBcs"
    "IDM4TCoYpGz7Nvz19VipFHY2R7anh2t/f4+W1lae+vnPNIDcvGmjllKytKmJqe5LMDiAY1vY"
    "to1CgN9/o29qqmnYvZvosmVMjYyQm5zAjCco3/EL3PnzsZNJHMuiLBolvriJKSmxHIe8VtiW"
    "xeXDh1ja1FSonoDRtmLFrmW33EJjdQ1jb72F7OnBVS6uYZIeGiR96hRld9wBfj+u62JZFm4k"
    "Qri1jczx47iGQc2uXbhz5+Ikk+Rtm6raWkqCQQ7edx+TR49iWBZOKoWVTKIdRWL1aiYch3h1"
    "9S5jRWvrrlWrVhEaHSf30UeI9BSuW7CXNk0mLlwkeeokkdtvR4TDWNksTjZLPhAgvHw5RksL"
    "dm0t+WSSXC5H1Zw5lIZCvH333WQ//5yQ1rhKoZVCKIXQmmhjI7758znb2YkUShGPx5m60oOa"
    "SuE4Lo5yCwp3XcySEkba2+l88klSAwM4hkEulyN9/TqpYBC3ro58KoVlWVTX1RELh3l7zRqs"
    "L74gXKwNoig2AahslrGODuLxOEIpJFJSUV5ObrAPncuS14q8q1DKKdjNtTFiMa59+k/ObtzI"
    "5LlzZGybXC5HPpPBnprCcRzm1NYSC4f58/r1WCdOECr+KQ2tMQCjCKFtm4nzXVSUl4OUSKUU"
    "kWiU1PkLqLw9o+y87eIohQPkRkbIDwzR/8EHXN65k1wmg1204PQIh0L84/HHSbe3E1UKWXyh"
    "BITWBRCtMVyXzMgwkWgUVbwPpRRGJDLja8d1cQAnnyfT3U16YICsEIQrKih75BEs18W2Ck6x"
    "7QL0F+fOUXP//dTV1+POerkBeGYdPQCmida6UAeklCQnk3irqrGhUNulIJ9OM9XVVVitEATK"
    "yki89hrOsmWoXA7HtrEBDANcF2VZTJaXU7t7N7H6egBMrTG1xjtr+IQgUFVFKplESolEKUZG"
    "RwnOTeAASkqsTJZ0Tw+WEOSEwFdWxtw9e7AXLkSn04VvnkiwZOFCpgYGsA0DKQSmbZOrrmbe"
    "3r2UJhLw1dVrjUdKShsbGbl2DZRCaikZ6O8jNL8BR0gcyyLT3Y0jBC7gD4WY9+qrOIsWodNp"
    "7Hye2kSCaDDIX++9l2tPP40zPIIIBvH7fPiUwpw3j8W//x2l8ThSa3zTqwcyCCqWNzM0NISW"
    "smDDy1cu46+rwxGQ7u3FFgIbMAMBFrz+Os7ixeipKRzbpnbuXKLBIH9Zv57cmTOYQ0OkfrkD"
    "PTKCNxYjFAjg05rwkh9w68GDhCuqCisvDl1WRsXyZnp6LhVs6AJfXvgSHQyhw2FsKQsCFAId"
    "jWKXleHm89i2TTyRoCQQ4NC6deROnCBSVLG6epXJ7dvRQ0MEKyoIhUKEAn5EXR1uOIgX8EuB"
    "6ffTsHULRlUNXee7CmLdt/+AUErxZXc3Cx54AOX340qJBiZHRuh+5hky/f3UNjQQDQZ5e+1a"
    "rI4OwkWfi6LYuHSJoU2bcPr6KK2owJqY4LMNG9CXLxMwDHzSYFBKKn/YxpnOs7hKsW//ASEB"
    "UqkUx9vbqVm3jtDixRjBIA6ghWD83Dn6du5k8vRp/nTfvVgnTxIsWmi6whlFCHn1Kn0PP8zg"
    "oUN0PPQQ5vvvU2kYeKVE+QN429qINC3l+LF2UqnUjTuiZ7c/o1fddhvNlZW89+AGnPHr5CwL"
    "VfwJOoAJBLRGTltsWtmAt3huao0jBAGtiXo8mEKQ93jojEZZffAgnw0P89HHH/PCiy/duCMa"
    "Hx/nREcHwz4frc//Ck8kgunz4Rave4sAs0NMl9hiuTW1xmsYlApB1OPBIwSO18s5v5+23a8w"
    "6PHw2YkTjI+Pz8wxA/DG3n1isLeXd48cwb9yJa0vvYSntJRgIIArxEwmZj9oTGdjGkYIDCkx"
    "DQNDCLJeL50lJbTu2YOxYjlH3nmHwd7eG3qEf7str7Ysjm5/luEzpzHyeRzbxpiVcq/WBYUX"
    "LRaQJl5TokyTXq0xVv6IlS/8mgEpv9+2fDq+2pgkOzvpP/I3Lr71R+zJCQJKYToOplL4KVY5"
    "wyAlJWkpKbvrLhb+9EFit6/i2PHj/1ljMh2zW7MVLS0sbWpCTUwwdfEiE52djJ78nMmeSzip"
    "KSKJekpvbqSq+VZitzYjKivp7Oyk/b9tzWbH/605/SaQ/0V7/i9mxCoPeTuiPgAAAABJRU5E"
    "rkJggg==")

ArtProv_INFORMATION = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAACFFJ"
    "REFUWIXFl01sXNUVx3/3vvdmxjOeceyxnRIrBFwkBxIKtbERpd9pVcEiokSVStRFJfIBpRKV"
    "InVBt11UqrLqopCERYVEVdRVKtFNP1TaUsWOU0TjYENj5wMnDvZkMt/vzbv33C7ezMQRoVBV"
    "VY/0NCO9mXP+55z//+gcpbTHJ7FDBw84D3Bao0RAa0QEAK01iPTeWeDY8RPqk/hVHwfg0MED"
    "Lp/Po7VmYmKC8fFxxsbGKBaLFAoFAKrVKqVSidXVVZaXl1laWkJEqNVqHwvkIwE8c/iQGxwc"
    "ZKBQYHpmhl27dlGpVLm8eo2NG21u1BX1FsRxhJg6fX6bO0ay3L97guHiEAsLC8zNzlKpVimX"
    "y7z40rHbArktgGcPPO3u2L6dqclJpmdm+Of5FSqtDO9Xh1lZMzRCR2wcsRGsCCIxykSICUlT"
    "ZmtujUcndzD52fuZm51l/swZrl6+zM9PvPwhEB8CcPjQQXfXjh089vjj9OfznL94nQu1cZYu"
    "tWhEGusURhRxLDSalthaAi0EWnDSRrkQJS1Srsynh66w/8kv02o1+e3rr3Ph4kVeOnZcfSSA"
    "Zw887e68+26e2r+fax98wOqNPKeXC2xUHbELEOuIBZwIRuDR3TmGt3i88fcKl67WCXwQMWBj"
    "tGsSUGXIu8h39t7HXTu288tXX+XSysotlegBeObwIbdt2zb27t1L1G6zeLXA3Pk09dAjlgBx"
    "DucUzglRZDn8xCjfeCgFQCOGHxy9wMWrLTzPIWIQa9EuIq0qbPEucWDffWwZyHPy5EmuXLnS"
    "44TuIhkcHGRqcpL+fJ6FCzD7XoobDUUr1hgTY4zB2pgoislm4GtTqV7lcgHsmeqj1mwjYjHG"
    "YY0QGU29nWU93MaJX82TyfQxNTnJ4OBg778aEql12f7Hv7zF2bURSjWhFTnitqEdCza2mNgm"
    "8qpHrFwxt3DnH4tX8QAxgljBisMaR2x8Gu0sa60xjr/yOtMzMwwUChw6eMAB+AD5fJ7pmRnO"
    "LpzjQu0erq6HhLEPzuJwuG4UBw5HGAk/+cUK33tiC8UBj5N/WOZPZ5qk+wYxJim/FcE6lwwo"
    "qxGV4+1LA5yaO8P0zAzrGxsJBw4fPuwGBgY4cuQIr7z2OxYqD1KuKqx4OKXA9cJ3eAAKqDdi"
    "orCJkiaRSVEo5PG0YK0g1iJik+9OcNYAMRldYWfxPD9+4bscPXqUSqWC7wETExOUSte5Ut/K"
    "jUqbyKZwzpKESlJ3jgSMA2uE/rSmkM3jXB6tHPVGSKlURawlNgYRi7MOtEOh8bTDBIrz1/q5"
    "du0Ddu7cyelTp/Cd1oyPj/PW2+e4Vh0lMoK1tlN2BcItIMQpwPHU1zM8+dUizUaLxUuOZ374"
    "MivlHQwMpDtVUyiVtEw5UEoR+gaX8fnzm/PcN3E3c3NzaCXC2NgYF1dLNEJot8EYizFCbCzG"
    "dp+EWK1mSGl9g91jFd5bfJdz77zL+Kcs6ZQCp9DKRysPrTTgofBQygM0VjzaxuPs4vuMjY2h"
    "RPDRmmKxyPr1mNiCsYK4hHCbhgVihEq1QmmjjO9rYikQh03CMEJEcEKvZc5tHnaqR2MnChGP"
    "S2t1isUiaI0vIhQKBZqRJo4FawziNDiVuFOKMAy5XrpOGIY4B77ng1hajRZhmGg/iaCS4JvA"
    "bzanFFY0jaamUCggIokMgUQ2VjC2k40ChaLeaHKjfAOxgqc9rDhwGhGI2iHG2JtCUUkbPmyq"
    "o2EFSt2Cz9daU61WCXSE2DZiPaRDmkatQbVWBQGtNK5TRqU04qAdtxHRqE5M5RSqN1xvhum2"
    "QCmFhyObtlSrVbTW+IhQKpUYGlCY9TZOAhBHvRVRq9W5KcWuz67jRB6e53V+okgGqw+4zQJG"
    "AQqLxuFpx9hoH6VSCUTQTmtWV1cZ374VX1o4MbTCkHq9gVKbZOi6QVTHpSYIUqTTGTzPQ6FQ"
    "+CjlofFAeSQq8BMl4KG1wsYhD+7ewerqKk7rRIbLy8tMT32GnF/B2YhGq5UEcwr05qCdLEWh"
    "FfT1Zchms/i6SyXdA9GVn1K683iktKPPq/HFRx9iZWUFJYK2wNLSEqOjI9w1dB0b1dBi6FFF"
    "6ChCdeikAU0mkyKbzZHrz+EFPkol/Vd4gL8p8+Qz8CDlx9y7vcHWraMsLS5iAX3s+AklIiws"
    "LPDYngcI3AaBF/dyvpUDulMNCNJ9DAwUGCkOk06lOgpIBtDNzD00Gk9pUr6g43X273uEc+fO"
    "YUU4dvyE0gC1Wo252Vlmpqd4+J4qKVoE2vbUk5DL62WPg2wmx8jwVoZHRlDa63BfobvTDx+F"
    "RmtF4FuyQZNHdjd4eGaS2VOnqNVqdD1z7PgJValWmZud5bmD32J7YYWM1yTQtlPamyxXaMRC"
    "f3+WoeEifX19yVutodNvrTSeUvhKEXhCf6pJMfMuR76/j9Nzc1Sq1d663tuIyuUy82fOEEUh"
    "Rw7tYTR7mYxukPIMSiU/7PZZLJxZuEIYGqIo5OzSOlFo8JXugEw6EviG/nSDgr/Ej57/Cq1W"
    "i9Pz85TL5V5XP3IpXV6+wE9f/D2XK+O0XY7YZBDngwsQ0Yym5hjqjxCnsdZxtf4gkQzj++Ap"
    "Q+BFpP06I33v8MLzX+LOO8f+/VLatc1reTqd4Wcvvsabi1uIZBghh5UU4gJaLUfcjpJstUd/"
    "Lkc6BZo2gW6h7Bqf21Xm+ee+SbPR+GRr+eZKbD5M3vzbLL/+zRxLq0O04kGcyuFIAUEiPWXR"
    "yiK2ScZb597tZb6972Gmpx74zw+Trt3uNFtbu8Ybf53n7YXLrG0YGq0AgFyfZdtoigd2jfGF"
    "zz/E6Mjwf3eabbb/23F6OyD/i/P8X/r+pANC4mXtAAAAAElFTkSuQmCC")

ArtProv_QUESTION = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAACTZJ"
    "REFUWIXFl22MXFd9xn/nnHvvrHd2Znc8drxev4TFsZMQvFDi3Y1QYyCgFNogOQQJJUL9UL8l"
    "lC8VVBWVUJP2SyuhSEUtDY6pEIJQqYKmbSgtIqGJS5J9cYidxGTXcdaO9y0ej2d3Zmdm7z3n"
    "/E8/zHoDilOQUMWRru69urr3ee5z/s9zzl8pbfh1xpHDh4IBgtYoEdAaEQFAaw0i6888cOzR"
    "4+rX+a76VQSOHD4UCoUCkTHs3rOHwcFBtm/fTrlcplgsAlCv16lWq8zOzjIzM8PZ6Wmc9zQa"
    "jV9J5B0J3H/0SCiVShR6ehgZHWVoaIharcbc/JssrSgqjYQ3FlpYK5R6c2zdCOUey55dA5Q2"
    "ljh9+jTjY2M0Vlao1Wo88vVj1yRyTQIPHDoYtu7YwfC+fQyPjHDu3DlWVmPOVfo4ObOBi4uW"
    "lZZHaRDxOGfx3pFEns0Fy203NPjg3jw337SLifFxJiYnWbh4kX84/o23kXgbgaNHDod3XX89"
    "f3DXXeTzeeYWl3i9to2x6YgLCxmrqykEj0LwQQjiCSJ48QTxWOdJU0s+8dw13OQzn9hNq9Xi"
    "B088wfkLF/j6sUfVOxJ44NDBsHNwkHvvu49qtcpyVuKZM32cOpdyZXkVowSFxznBeY/1nuAd"
    "aMEgaBUIwePXnjWbGXt3rvKFe/sZ2Hod333sMd6YmfklJdYJ3H/0SBgYGODAgQNYa7mcbuMH"
    "ExFnXm/inCPSgTSzpE7oy2u2lA3lYgQIl6+kzFeaXK61MSZgNIhYCEKzZdlcSPnrB3ZQLHTx"
    "+OOPMz8/v14T0VUmpVKJ4X37yOfzTL3h+I9ThpfP1jFKMEpIrWdLOebeOzdz+/sLbCq+JaP1"
    "UL2S8uOJCt/8txkWq21ycUC8JxcH5q/An39tiuN/cRvD+/bxzIkT6+9qWLNaTw/DIyO8+NJr"
    "PDNd5ufnGmgc4PDesZqmfPbjm7h7/y+DA8QG+jfFfPb3t/K3X7iF/pJidTXDi8V5Sy4OzFxS"
    "/M2xnzI8MkKhp4cjhw+FdQKFQoGR0VHOnDnDbOtGpmaaWJsBnfn03hHEE2t/LScB4EWRpsIt"
    "u/s4es/12CxDvIB4CJZ8l+K/Ji3/8/xpRkZHKRQKHQWOHD4UImMYGhpi+vwyr87nqNSaKATn"
    "HN5nSLCId6jgAMuJ8bN85fiz/NnDJzj2z6dprKRopdDaYG1g/we2srEgiHjAoRBASLoi/vHx"
    "KYaGhoiMoYMN7N6zh0qlwkJzgIsLTYJ4RAWCOAIdm2nleHpyjv98+gWenGyRSUIA0tUKlZrn"
    "SwffiwgoNIWemL4eYanVcQYIikAuUrx8IXD+jQX23Hgjk2NjREFrBgcHOf3yNFOX3sNSow1Y"
    "ggghCCJCEIdG+OGzNaxXdHUXyQUPQWgEw5nXl7lcXSYyEXEck2aeNysNluuaSAUUHRJaQzsN"
    "/PuTp/jI8CATExNoJcL27duZv9TkzYrFu07QiDjEWby3ON+5j2PPhpwCsWSpZane4nKtyUBf"
    "yqWFeSqXa3hvefHns8xXWiCeEDwhCCEEvBdiAz99YZFt27ahRIjQmnK5zEJNaKe2A+47xReC"
    "rCsBDvGe1dTSamc02ymttuOO3+nmI3s11VqdUilGxPPNf/kZ1mt6cmGtRAMKOofRLF4JlMtl"
    "0JpIRCgWi1SXOnZzLiOEsM6c4AniaKeWViulvdrJfQh86vY8n96fx3tHZh1xBI88NsaPxy9T"
    "LPSglUC4mngQgu6cdUKxWERE3goicSnWWYLYdQIqeLLMsdxo004tIp01ILOOu2/v448+3svK"
    "qkPriFwu5uFvTfLD55boLRYxClD6LZ8G3eEShEitwxJpranX63QnDm9TCI4QPIjQyjKWGm2c"
    "7RQcQRBxlAoR99yxhSinyRshBPjqd15mbEroK/UR6TW51brwa+AQAsShSb1eR2tNhAjVapX+"
    "siKdaRMpAGE1S6ktt/G+Ax6CBwRrPe/q72ZHfy8iQikX8e0nXmJ82rG5XEKrgFZmDVyjUGtV"
    "ABKAoOiNoVqtgkjHhrOzs+wcKJGP2jRthLOW2nILL7LmCL/m5Q65QrfG4IkjhVaB83OrFAq9"
    "xEZjTIRSHWC1NgVh7c+DdNaN993Uy9zcHEFrIiXCzMwMo6OjlH/yHMutjSwtt3DOAuEtcAmo"
    "KNDdpbiw2OQr3zqF0RBFmouXPD1deeLIoJRBKwWYjvwBQudE0CBpi7vuuIWZ106hRNAeODs9"
    "zZYtW7h5a4MrSy0ymxGCR5zt5IF3gMcoyCWKetNx4pWMUzOKyWlN0xZJ4hijE7RKgBwQv+0I"
    "xGzK17nlxh2cnZ7GA+aFn7340G23jT5YLBYZ3LGJp8dnqLcj1Jr0YW33YxQkSUfaXdvy3H9g"
    "gAO/W+LD+zbhyTG76DEmorPCRxAiAmbt2gCadjtw8O4esnaVqakp/u7vv9aZpEajwfjYGMPD"
    "+7jzfSmZXcWLQ65mAQFtQCshSTSf+eh1vGdnglGOQpJx750b2dgb4X0CEhMkQiQiuBhvI7wz"
    "WBuzvTTLJ3/vVsaef55Go8H6cnzs0eOqsbLCxPg4nz98Dx/cVaGd2bUgEowKRDpgjKYrMfRv"
    "7iGKu8h1bcAkOQrdMTktiI+QEOFdhLUxmY9wPsL5BEkXeehPRjk5OUljZWV9u76eFLVajYnJ"
    "SbIs48uf/xi37lzCOtcpQBWIjCYyBufguZcaFHsLDPSX2dZf5sVXq8xdEhQdYOsivDc4Z3Au"
    "wqdVvvzAdcTGMz4xQa1WWw8ic9UqkydPPnTTDbsevFSpsH//fm69eSOvnnmJxXoXSWxIYkMu"
    "ielKYs4vZLw22+TS5Rb/PVnlX59sILpMCBHea7wYvNV4H5GoC3zpaC8f2Hs93//e95i7cIFH"
    "fqFZ+T+35UmS8FcP/xPPTsVY+ujpTtjQlSOOuhAxeKfRuotckid4g3URzkVYZxC7yg0DU/zl"
    "F0cwyr7jtnxdgavj5MkXHtrz7sEH5xYW6N6wgYN/eDd7tlquvPka7RTQ3egoRy6K6Uo2kMQ5"
    "CAaRGOcjlKuxpTjF5+5L+NM//hDTr77CU0899bY/f0cFro5rtWYXZ+f50U8meWW6wpWGop0m"
    "QExkYGNRs3uwyCc+upfd7x74zVqzXxy/teb0WkT+P9rz/wUcXFH/JQ1qxwAAAABJRU5ErkJg"
    "gg==")

